resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: Dshahi14
    name: Dshahi14/React-JS-Sample-Code

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: MyGitHubRepo


- script: dir $(Build.SourcesDirectory)