resources:
  repositories:
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: Dshahi14
    name: Dshahi14/create-react-app
  - repository: template # The name used to reference this repository in the checkout step
    type: github
    endpoint: Dshahi14
    name: Dshahi14/abc

trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage:
    jobs:
     - job:
       steps:
        - checkout: MyGitHubRepo

